name: snapchat
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.13.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  google_sign_in: ^6.1.6  
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.22.0
  firebase_database: ^10.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
